#server:
#  port: 2220
#spring:
#  application:
#    name: gateway-service
##  cloud:
##    nacos:
##      config:
##        server-addr: 127.0.0.1:8847
##      discovery:
##        server-addr: 127.0.0.1:8847