spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ms_2
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
jwt-data:
  jwtSecret: kimhab
  accessExpirationMn: 840
  refreshExpirationMn: 850

server:
  port: 1112

logging:
  level:
    root: info